package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGendocs(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "cli-ref")

	rootCmd.SetArgs([]string{"gendocs", dir})
	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("gendocs failed: %v", err)
	}

	// Root command page must exist.
	rootPage := filepath.Join(dir, "intuneme.md")
	if _, err := os.Stat(rootPage); err != nil {
		t.Fatalf("expected %s to exist: %v", rootPage, err)
	}

	// Spot-check known command pages.
	for _, name := range []string{
		"intuneme_init.md",
		"intuneme_start.md",
		"intuneme_stop.md",
		"intuneme_status.md",
		"intuneme_config.md",
	} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			t.Errorf("expected %s to exist: %v", name, err)
		}
	}

	// Hidden commands (gendocs itself) must NOT generate a page.
	if _, err := os.Stat(filepath.Join(dir, "intuneme_gendocs.md")); err == nil {
		t.Error("gendocs is hidden — should not generate its own page")
	}

	// Auto-gen tag must be suppressed.
	data, err := os.ReadFile(rootPage)
	if err != nil {
		t.Fatalf("read root page: %v", err)
	}
	if strings.Contains(string(data), "Auto generated by spf13/cobra") {
		t.Error("expected DisableAutoGenTag to suppress auto-gen footer")
	}
}

func TestGendocs_CreatesOutputDir(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "nested", "deep", "cli-ref")

	rootCmd.SetArgs([]string{"gendocs", dir})
	if err := rootCmd.Execute(); err != nil {
		t.Fatalf("gendocs failed: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, "intuneme.md")); err != nil {
		t.Fatal("expected output directory to be created automatically")
	}
}
